### DISCUSSION TITLE
JSI::Schema::ReferenceError - cannot find schema

### DISCUSSION THREAD

**Discussion by makemp** [notEthan/jsi#288] [Q&A] [answered]
I have a problem with `ref` marker in yaml.

I have code:
`JSI.new_schema(YAML.load_file(file_path))`
Which raises an error 

```
   JSI::Schema::ReferenceError:
       cannot find schema by ref: ./definitions.yml#/definitions/draft
       from: #{<JSI (JSI::JSONSchemaOrgDraft07) Schema>
         "$ref" => "./definitions.yml#/definitions/draft"
       }
```
Because it loads a file which looks like that:

```
$schema: 'http://json-schema.org/draft-07/schema'
description: 'desc goes here'
required: ['person']
properties:
  person:
    $ref: "./definitions.yml#/definitions/draft"
```
And `definitions.yml` file is in the same dir as 'file_path' file
and looks like that:

```
$schema: 'http://json-schema.org/draft-07/schema'
definitions:
  draft:
    type: object
    properties: ...
```

I do not know what I am doing wrong but It would be great to share definitions outside the file.
Any ideas?
Thaank you
